// <auto-generated />
using MeloManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeloManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200826184516_HomeLaptopCreate")]
    partial class HomeLaptopCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeloManager.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 3,
                            Email = "32L@YJO0.com",
                            Name = "VWLCN"
                        },
                        new
                        {
                            Id = 2,
                            Department = 3,
                            Email = "OSG@OO7B.com",
                            Name = "ARYRY"
                        },
                        new
                        {
                            Id = 3,
                            Department = 3,
                            Email = "UJC@XUV2.com",
                            Name = "ZTV9F"
                        },
                        new
                        {
                            Id = 4,
                            Department = 3,
                            Email = "U83@EU7V.com",
                            Name = "48Z8J"
                        },
                        new
                        {
                            Id = 5,
                            Department = 3,
                            Email = "YVG@YKM4.com",
                            Name = "N7COT"
                        },
                        new
                        {
                            Id = 6,
                            Department = 3,
                            Email = "LCP@65X0.com",
                            Name = "H3GD9"
                        },
                        new
                        {
                            Id = 7,
                            Department = 3,
                            Email = "E6F@W9VH.com",
                            Name = "ZT73Q"
                        },
                        new
                        {
                            Id = 8,
                            Department = 3,
                            Email = "ODT@V50P.com",
                            Name = "S4T98"
                        },
                        new
                        {
                            Id = 9,
                            Department = 3,
                            Email = "RZR@KLZ9.com",
                            Name = "N433R"
                        },
                        new
                        {
                            Id = 10,
                            Department = 3,
                            Email = "GHH@I9UE.com",
                            Name = "110UN"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
